Document: surrogate
Title: Debian surrogate Manual
Author: <insert document author here>
Abstract: This manual describes what surrogate is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/surrogate/surrogate.sgml.gz

Format: postscript
Files: /usr/share/doc/surrogate/surrogate.ps.gz

Format: text
Files: /usr/share/doc/surrogate/surrogate.text.gz

Format: HTML
Index: /usr/share/doc/surrogate/html/index.html
Files: /usr/share/doc/surrogate/html/*.html
